import { readFile } from "node:fs/promises";
import path from "node:path";
import type { EvaluatorFixture } from "@/lib/benchmark/generator";
import type { FrozenPolicyPlans } from "@/lib/benchmark/evaluator";
import { datasetManifestSchema } from "@/lib/domain/schemas";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
async function comparisonData() { const root = process.cwd(); const [datasetRaw, plansRaw, fixtureRaw] = await Promise.all([readFile(path.join(root, "fixtures/public/recovery-cases-v1.0.0.json"), "utf8"), readFile(path.join(root, "fixtures/public/frozen-plans/recovery_os.json"), "utf8"), readFile(path.join(root, "fixtures/evaluator/potential-outcomes-v1.0.0.json"), "utf8")]); const dataset = datasetManifestSchema.parse(JSON.parse(datasetRaw)); const plans = JSON.parse(plansRaw) as FrozenPolicyPlans; const fixture = JSON.parse(fixtureRaw) as EvaluatorFixture; const cases = new Map(dataset.cases.filter((item) => item.split === "heldout").map((item) => [item.case_id, item])); const outcomes = new Map(fixture.outcomes.map((item) => [`${item.case_id}|${item.action}|${item.delay_minutes}`, item])); const groups = new Map<string, { cases: number; recovered: number; gross: number; actions: Map<string, number> }>(); for (const plan of plans.plans) { const item = cases.get(plan.case_id)!; const outcome = outcomes.get(`${plan.case_id}|${plan.action}|${plan.delay_minutes}`)!; const group = groups.get(item.failure_code) ?? { cases: 0, recovered: 0, gross: 0, actions: new Map() }; group.cases += 1; group.actions.set(plan.action, (group.actions.get(plan.action) ?? 0) + 1); if (outcome.recovered && outcome.recovery_delay_minutes !== null && outcome.recovery_delay_minutes < 2880) { group.recovered += 1; group.gross += item.amount_paise; } groups.set(item.failure_code, group); } return [...groups.entries()].map(([failure, value]) => ({ failure, ...value, actions: [...value.actions.entries()].sort((a,b) => b[1]-a[1]).map(([name,count]) => `${name} ${count}`).join(" · ") })); }
export default async function ComparisonPage() { const rows = await comparisonData(); return <main className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-8 sm:px-6 lg:px-8"><PageHeader eyebrow="Benchmark evidence" title="Recovery by failure category" description="Observed outcomes from only the selected RecoveryOS action and delay on the frozen held-out batch." badge="Recovered — simulation" /><Card><CardHeader><CardTitle>Category breakdown</CardTitle><CardDescription>Projected probability never counts as recovered revenue.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Failure category</TableHead><TableHead>Cases</TableHead><TableHead>Recovered</TableHead><TableHead>Gross recovery</TableHead><TableHead>Selected actions</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.failure}><TableCell><Badge variant="outline">{row.failure}</Badge></TableCell><TableCell>{row.cases}</TableCell><TableCell>{row.recovered}</TableCell><TableCell className="font-mono">₹{(row.gross / 100).toLocaleString("en-IN")}</TableCell><TableCell className="text-xs text-muted-foreground">{row.actions}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></main>; }
